account/urls.py
from django.urls import path
from .views import checkdetails, register, customer
from django.contrib.auth import views as auth_views

app_name = 'records'

urlpatterns = [
    path('check-customer-details/', checkdetails, name='checkdetailsview'),
    path('customer-records/', customer, name='customerview'),
    path('register-records/', register, name='registerview'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logoutview'),
    path('register-records/register', register)
]

home/urls.py
from django.urls import path
from .views import home, contact, about

app_name = 'home'

urlpatterns = [
    path('', home, name='homeview'),
    path('about/', about, name='aboutview'),
    path('contact/', contact, name='contactview')
]

hotelsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('account/', include('account.urls'))
]

account/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    Occupant_name = models.CharField(max_length=100)
    Occupant_email = models.EmailField()
    Occupant_occupation = models.CharField(max_length=100)
    def __str__(self):
        return self.Occupant_name

class Record(models.Model):
    Room_number = models.IntegerField()
    Amount_paid = models.CharField(max_length=20)
    Num_of_nights = models.IntegerField()
    Start_date = models.DateField()   
    End_date = models.DateField() 
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=False)
    def __str__(self):
        return f'Record for {self.customer}, {self.End_date}'
    

account/views.py
from django.shortcuts import render, redirect
from home.models import Customer, Record

# Create your views here.
def register(request):
    if request.method == 'POST':

        occupant_name = request.POST.get('Occupant_name')
        occupant_email = request.POST.get('Occupant_email')
        occupant_occupation = request.POST.get('Occupant_occupation')    #Customer details terminates here

        room_number = request.POST.get('Room_number')                            
        amount_paid = request.POST.get('Amount_paid')
        num_of_nights = request.POST.get('Num_of_nights')
        start_date = request.POST.get('Start_date')
        end_date = request.POST.get('End_date')
        customer = request.user                                          #Hotel record pertaining to customer terminates here

        new_customer = Customer(Occupant_name=occupant_name, Occupant_email=occupant_email, Occupant_occupation=occupant_occupation)                              #to save the data from the Customer frontend to the database
        new_record = Record(Room_number=room_number, Amount_paid=amount_paid, Num_of_nights=num_of_nights, Start_date=start_date, End_date=end_date)  #to save the data from the Record frontend to the database
        new_customer.save()
        new_record.save()
        
        return redirect('records:registerview')
    return render(request, 'records/register.html')
   
def checkdetails(request):
    return render(request, 'records/checkdetails.html')
def customer(request):
    return render(request, 'records/customer.html')

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home/index.html')
def about(request):
    return render(request, 'home/about.html')
def contact(request):
    return render(request, 'home/contact.html')

account/templates/records/checkdetails.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->

{%extends 'home/index.html'%}
{%load crispy_forms_tags%}


	{%block body%}

	<!--/banner-->
	<div class="banner-inner">
	</div>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Home</a>
		</li>
		<li class="breadcrumb-item active">Sign in</li>
	</ol>
	<!--//banner-->
	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
				<h3 class="tittle">Sign In Now</h3>
				<div class="row inner-sec">
					<div class="login p-5 bg-light mx-auto mw-100">
					<form action="#" method="post">
						{% csrf_token %}
						{{form|crispy}}
							<div>
								<button type="submit" class="btn btn-primary submit">Login</button>
							</div>
					</form>

					</div>
				</div>
		</div>
	</section>
	<!--//main-->

	{%endblock body%}
	

account/templates/records/logout.html
{%extends 'home/index.html'%}

{%block body%}
<div style="margin: 50px:">
    <div class="container">
        <p>You're logged out!</p>
            <p>Click the <b>link</b>below to log in</p>
        <div>
            <a href="{%url 'records:checkdetailsview'%}">Login</a>
        </div>
    </div>
</div>
{%endblock body%}

account/templates/records/register.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% extends 'home/index.html' %}


    {% block body %}
	
	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
			<h3 class="tittle">Register New Customer</h3>
				<div class="inner-sec">
			<div class="login p-5 bg-light mx-auto mw-100">
				<form action="register" method="post">
					{%csrf_token%}

								<div class="col-md-6 mb-3">
										<label for="Ocuupant_name">Occupant name</label>
									<input type="text" class="form-control" id="Occupant_name" name="Occupant_name" placeholder="" required="">
								</div>
								<div class="col-md-6 mb-3">
										<label for="Occupant_email">Occupant email</label>
									<input type="email" class="form-control" id="Occupant_email" name="Occupant_email" placeholder="" required="">
								</div>
								<div class="col-md-6 mb-3">
										<label for="Occupant_occupation">Occupant occupation</label>
									<input type="text" class="form-control" id="Occupant_occupation" name="Occupant_occupation" placeholder="" required="">
								</div>
						
						
								<div class="col-md-6 mb-1">
										<label for="Room_number">Room number</label>
									<input type="number" class="form-control" id="Room_number" name="Room_number" placeholder="000" required="">
								</div>
								<div class="col-md-6 mb-3">
										<label for="Amount_paid">Amount paid</label>
									<input type="number" class="form-control" id="Amount_paid" name="Amount_paid" placeholder="Any currency" required="">
								</div>
								<div class="col-md-6 mb-3">
										<label for="Num_of_nights">Num of nights</label>
									<input type="number" class="form-control" id="Num_of_nights" name="Num_of_nights" placeholder="1" required="">
								</div>
						
							<div class="col-md-3 mb-3">
									<label for="Start_date">Start date</label>
								<input type="date" class="form-control" id="Start_date" name="Start_date" placeholder="" required="">
							</div>
							<div class="col-md-3 mb-3">
									<label for="End_date">End date</label>
								<input type="date" class="form-control" id="End_date" name="End_date" placeholder="" required="">
							</div><br>
							<button type="submit" class="btn btn-primary submit mb-4">Add Customer</button>
								<p>
									<a href="#">This means the customer agrees to our terms of service</a>
								</p>
				</form>
		
				</div>
			</div>
		</div>
	</section>
	<!--//main-->
	<!--footer-->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left">
					<h3>About US</h3>
					<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>
					<div class="read">
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</div>
				</div>
				<div class="col-lg-4 footer-grid-agileits-w3ls text-left">

					<div class="tech-btm">
						<h3>Latest Posts</h3>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/4.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/5.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
						<div class="blog-grids row mb-3">
							<div class="col-md-5 blog-grid-left">
								<a href="single.html">
									<img src="images/6.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="col-md-7 blog-grid-right">

								<h5>
									<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
								</h5>
								<div class="sub-meta">
									<span>
										<i class="far fa-clock"></i> 20 Jan, 2018</span>
								</div>
							</div>

						</div>
					</div>
				</div>
				<!-- subscribe -->
				<div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
					<h2>Signup to our newsletter</h2>
					<div class="subscribe-main text-left">
							<div class="subscribe-form">
									<form action="#" method="post" class="subscribe_form">
										<input class="form-control" type="email" placeholder="Enter your email..." required="">
										<button type="submit" class="btn btn-primary submit">Submit</button>
									</form>
									<div class="clearfix"> </div>
							</div>
						<p>We respect your privacy.No spam ever!</p>
					</div>
					<!-- //subscribe -->
				</div>
			</div>
			<!-- footer -->
			<div class="footer-cpy text-center">
				<div class="footer-social">
					<div class="copyrighttop">
						<ul>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-facebook-f"></i>
									<span>Facebook</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-twitter"></i>
									<span>Twitter</span>
								</a>
							</li>
							<li class="mx-3">
								<a class="facebook" href="#">
									<i class="fab fa-google-plus-g"></i>
									<span>Google+</span>
								</a>
							</li>
							<li>
								<a class="facebook" href="#">
									<i class="fab fa-pinterest-p"></i>
									<span>Pinterest</span>
								</a>
							</li>
						</ul>

					</div>
				</div>
				<div class="w3layouts-agile-copyrightbottom">
					<p>© 2018 Weblog. All Rights Reserved | Design by
						<a href="http://w3layouts.com/">W3layouts</a>
					</p>

				</div>
			</div>

			<!-- //footer -->


		</div>

  	{%endblock body%}  

home/templates/home/about.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% extends 'home/index.html' %}

	{% block body %}
	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
			<h3 class="tittle">About</h3>
			<div class="row inner-sec">
				<!--left-->
				<div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
					<div class="blog-grid-top">

						<div class="blog_info_left_grid">
							<a href="single.html">
								<img src="images/b5.jpg" class="img-fluid" alt="">
							</a>
						</div>
						<h3>
							Amet consectetur adipisicing
						</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt ut labore et dolore magna
							aliqua uta enim ad minim ven iam quis nostrud exercitation ullamco labor nisi ut aliquip exea commodo consequat duis
							aute irudre dolor in elit sed uta labore dolore reprehender</p>
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</div>
					<div class="row">
						<div class="col-md-6 card mt-3">
							<img class="card-img-top" src="images/2.jpg" alt="Card-image">
							<div class="card-body">
								<h5 class="card-title">Lorem ipsum dolor </h5>
								<p class="card-text mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt.. </p>
								<a href="single.html" class="btn btn-primary read-m">Read More</a>
							</div>
						</div>
						<div class="col-md-6 card mt-3">
							<img class="card-img-top" src="images/3.jpg" alt="Card-image">
							<div class="card-body">
								<h5 class="card-title">Lorem ipsum dolor </h5>
								<p class="card-text mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt.. </p>
								<a href="single.html" class="btn btn-primary read-m">Read More</a>
							</div>
						</div>
						<div class="col-md-6 card mt-3">
							<img class="card-img-top" src="images/2.jpg" alt="Card-image">
							<div class="card-body">
								<h5 class="card-title">Lorem ipsum dolor </h5>
								<p class="card-text mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt.. </p>
								<a href="single.html" class="btn btn-primary read-m">Read More</a>
							</div>
						</div>
						<div class="col-md-6 card mt-3">
							<img class="card-img-top" src="images/3.jpg" alt="Card-image">
							<div class="card-body">
								<h5 class="card-title">Lorem ipsum dolor </h5>
								<p class="card-text mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt.. </p>
								<a href="single.html" class="btn btn-primary read-m">Read More</a>
							</div>
						</div>
					</div>
				</div>
				<!--//left-->
				<!--right-->
				<aside class="col-lg-4 agileits-w3ls-right-blog-con text-right">
					<div class="right-blog-info text-left">
						<div class="tech-btm">
							<img src="images/banner1.jpg" class="img-fluid" alt="">
						</div>
						<div class="tech-btm">
							<h4>Sign up to our newsletter</h4>
							<p>Pellentesque dui, non felis. Maecenas male </p>
							<form action="#" method="post">
								<input type="email" placeholder="Email" required="">
								<input type="submit" value="Subscribe">
							</form>

						</div>
						<div class="tech-btm widget_social">
							<h4>Stay Connect</h4>
							<ul>

								<li>
									<a class="twitter" href="#">
										<i class="fab fa-twitter"></i>
										<span class="count">317K</span> Twitter Followers</a>
								</li>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-facebook-f"></i>
										<span class="count">218k</span> Twitter Followers</a>
								</li>
								<li>
									<a class="dribble" href="#">
										<i class="fab fa-dribbble"></i>

										<span class="count">215k</span> Dribble Followers</a>
								</li>
								<li>
									<a class="pin" href="#">
										<i class="fab fa-pinterest"></i>
										<span class="count">190k</span> Pinterest Followers</a>
								</li>

							</ul>
						</div>
						<div class="single-gd my-5 tech-btm">
							<h4>Our Progress</h4>
							<div class="progress">
								<div class="progress-bar progress-bar-striped" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
						</div>
						<div class="tech-btm">
							<h4>Recent Posts</h4>

							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/1.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/7.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/4.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">
									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Feb, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/5.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/6.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/8.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">
									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Feb, 2018</span>
									</div>
								</div>

							</div>
						</div>
					</div>

				</aside>
				<!--//right-->
			</div>
		</div>
	</section>
	<!--//main-->
	{% endblock body %}

	

home/templates/home/contact.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% extends 'home/index.html' %}


	{% block body %}
		<!--/main-->
	<section class="main-content-w3layouts-agileits">

		<h3 class="tittle">Contact Us</h3>
		<p class="sub text-center">We love to discuss your idea</p>
		<div class="contact-map inner-sec">

			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d100949.24429313939!2d-122.44206553967531!3d37.75102885910819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSan+Francisco%2C+CA%2C+USA!5e0!3m2!1sen!2sin!4v1472190196783"
			    class="map" style="border:0" allowfullscreen=""></iframe>
		</div>
		<div class="ad-inf-sec bg-light">
			<div class="container">
				<div class="address row">

					<div class="col-lg-4 address-grid">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="far fa-map"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>Address</h6>
								<p> California, USA

								</p>
							</div>
						</div>

					</div>
					<div class="col-lg-4 address-grid">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="far fa-envelope"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>Email</h6>
								<p>Email :
									<a href="mailto:example@email.com"> mail@example.com</a>

								</p>
							</div>

						</div>
					</div>
					<div class="col-lg-4 address-grid">
						<div class="row address-info">
							<div class="col-md-4 address-left text-center">
								<i class="fas fa-mobile-alt"></i>
							</div>
							<div class="col-md-8 address-right text-left">
								<h6>Phone</h6>
								<p>+1 234 567 8901</p>

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="contact_grid_right">
				<form action="#" method="post">
					<div class="row contact_left_grid">
						<div class="col-md-6 con-left">
							<div class="form-group">
								<label for="validationCustom01 my-2">Name</label>
								<input class="form-control" type="text" name="Name" placeholder="" required="">
							</div>
							<div class="form-group">
								<label for="exampleFormControlInput1">Email</label>
								<input class="form-control" type="email" name="Email" placeholder="" required="">
							</div>
							<div class="form-group">
								<label for="validationCustom03 my-2">Subject</label>
								<input class="form-control" type="text" name="Subject" placeholder="" required="">
							</div>
						</div>
						<div class="col-md-6 con-right">
							<div class="form-group">
								<label for="textarea">Message</label>
								<textarea id="textarea" placeholder=""></textarea>
							</div>
							<input class="form-control" type="submit" value="Submit">

						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
	<!--//main-->
	{% endblock body %}
	